version: "3.9"

volumes:
  db-volume:

services:
  app:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SCHEDULER_DATABASE_HOST=db
      - SCHEDULER_DATABASE_PASSWORD=postgres
      - SCHEDULER_DATABASE_PORT=5432
      - SCHEDULER_DATABASE_USERNAME=postgres

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db-volume:/var/lib/postgresql/data
