---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/rooms":
    get:
      summary: Retrieves room list
      tags:
      - Rooms
      responses:
        '200':
          description: rooms found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Room"
    post:
      summary: Creates a room
      tags:
      - Rooms
      parameters: []
      responses:
        '201':
          description: room created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RoomCreate"
  "/rooms/{id}":
    get:
      summary: Retrieves a room
      tags:
      - Rooms
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: room found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Room"
        '404':
          description: room not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    patch:
      summary: Updates a room
      tags:
      - Rooms
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: room updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RoomCreate"
    delete:
      summary: Deletes a room
      tags:
      - Rooms
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: room deleted
        '404':
          description: room not found
  "/schedules":
    get:
      summary: Retrieves schedule list
      tags:
      - Schedules
      responses:
        '200':
          description: schedules found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Schedule"
    post:
      summary: Creates a schedule
      tags:
      - Schedules
      parameters: []
      responses:
        '201':
          description: schedule created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ScheduleCreate"
  "/schedules/{id}":
    get:
      summary: Retrieves a schedule
      tags:
      - Schedules
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: schedule found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Schedule"
        '404':
          description: schedule not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    patch:
      summary: Updates a schedule
      tags:
      - Schedules
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: schedule updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ScheduleCreate"
    delete:
      summary: Deletes a schedule
      tags:
      - Schedules
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: schedule deleted
        '404':
          description: schedule not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        detail:
          type: object
      required:
      - message
    Room:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - created_at
      - updated_at
    RoomCreate:
      type: object
      properties:
        name:
          type: string
      required:
      - name
    Schedule:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        room_id:
          type: integer
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - title
      - start_time
      - end_time
      - created_at
      - updated_at
    ScheduleCreate:
      type: object
      properties:
        title:
          type: string
        room_id:
          type: integer
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
      - title
      - room_id
      - start_time
      - end_time
